#index:
#    path: /
#    controller: App\Controller\DefaultController::index
customer_list:
  path: api/v1/customers
  controller: App\Controller\CustomerController:indexAction
  methods: [GET]
customer_create:
  path: api/v1/customers
  controller: App\Controller\CustomerController:createAction
  methods: [POST]
customer_delete:
  path: api/v1/customers/{customerId}
  controller: App\Controller\CustomerController:deleteAction
  methods: [DELETE]
  requirements: 
    id: '\d+'
product_list:
  path: api/v1/products
  controller: App\Controller\ProductController:indexAction
  methods: [GET]
product_show:
  path: api/v1/products/{productId}
  controller: App\Controller\ProductController:showAction
  methods: [GET]
product_create:
  path: api/v1/products
  controller: App\Controller\ProductController:createAction
  methods: [POST]
product_delete:
  path: api/v1/products/{productId}
  controller: App\Controller\ProductController:deleteAction
  methods: [DELETE]
  requirements: 
    id: '\d+'
product_update:
  path: api/v1/products/{productId}
  controller: App\Controller\ProductController:updateAction
  methods: [PUT]
  requirements:
    id: '\d+'
cart_show:
  path: api/v1/customers/{id}/cart
  controller: App\Controller\CartController:showAction
  methods: [GET]
  requirements: 
    id: '\d+'
cart_create:
  path: api/v1/customers/cart
  controller: App\Controller\CartController:createAction
  methods: [POST]
cart_update:
  path: api/v1/customers/{customerId}/cart
  controller: App\Controller\CartController:updateAction
  methods: [PATCH]
  requirements: 
    customerId: '\d+'
cart_delete:
  path: api/v1/customers/{customerId}/cart/{cartId}
  controller: App\Controller\CartController:deleteAction
  methods: [DELETE]
  requirements: 
    customerId: '\d+'
    cartId: '\d+'